### PR TITLE
Add Ukrainian translation

### LINKED ISSUE #20: Add Ukrainian translation

### PR DESCRIPTION
**Pull request by madtaras**
Fixes #20 Add Ukrainian translation

### CODE REVIEW

**Comment by cezarlz** [comment]
Please, update the README too. Insert UK on the translations available list https://github.com/cezarlz/boss-validator#messages

Thanks!

**Comment by madtaras** [comment]
@cezarlz Please review and merge

**Comment by cezarlz** [comment]
Ok, I will test before merge. But, is probably I will merge today.

**Comment by cezarlz** [comment]
Merged @madtaras

**Pull request merged**
